### ISSUE TITLE
Segnalazioni

### ISSUE THREAD

**Issue by sabas** [MarcoBuster/railway-opendata#1]
Ciao,
il repository mi è capitato sott'occhio nel feed, volevo segnalarti
* tanto tempo fa avevo dato una occhiata alle API anche io se può tornarti utile
https://github.com/sabas/trenitalia
* un gruppo di francesi nel 2014 aveva fatto una iniziativa simile
https://github.com/OpenDelays/opendelays

**Comment by MarcoBuster** [comment]
Ciao @sabas!

Era il 2014 e avrò avuto ~14 anni, non sapevo nulla di programmazione. Ogni mattina andavo a scuola in treno e volevo ricevere un messaggio con il suo ritardo; mi ricordo ancora di essermi imbatutto per caso nella tua documentazione e di aver iniziato a scrivere le prime (orribili) versioni di [OrarioTreniBot](https://github.com/MarcoBuster/OrarioTreniBot). Se diversi anni dopo sono al terzo anno di Informatica il merito è sicuramente anche tuo, quindi grazie. :) 

Sono quindi al corrente della tua repository, l'ho citata negli [appunti](https://github.com/MarcoBuster/railway-opendata/blob/master/docs/VIAGGIATRENO.md). Ero a conoscenza di OpenDelays, ottima iniziativa! Credo però che il mio lavoro sia più approfondito e specifico per i treni italiani.

**Comment by sabas** [comment]
> Se diversi anni dopo sono al terzo anno di Informatica il merito è sicuramente anche tuo, quindi grazie. :)
This made my day, ne sono contento🥇 

Se avessi bisogno di qualcosa pingami o mandami una mail!
